### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by ZZcat** [sketchfab/ksp-exporter#11]
Publish error: AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by AurL** [comment]
Hi, 

Sorry for the huge delay, I hope to be back on this soon.
Please note that a pending WIP branch is waiting for some updates to make the exporter compatible with latest KSP versions. I hope to push the updates asap, when I have time.

Thanks for reporting!
